name: Docker Image CI & CD for Emby Toolkit

on:
  push:
    branches:
      - main      # 监听 主 分支
      - dev        # 监听 开发 分支
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata for AMD64
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/emby-toolkit
          tags: |
            # 规则1: 如果事件是推送到一个分支，就用分支名作为 Docker 标签。
            # 这会自动为默认分支(main)打上 'latest' 标签。
            type=ref,event=branch

            # 规则2: 如果事件是推送一个 Git 标签，就直接使用该标签名作为 Docker 标签。
            type=ref,event=tag

      - name: Build and push AMD64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-arm64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    # 只在main分支或标签推送时构建ARM镜像
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata for ARM64
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/emby-toolkit
          tags: |
            # 为main分支生成arm标签
            type=raw,value=arm,enable={{is_default_branch}}
            # 为Git标签生成arm标签
            type=raw,value=arm,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push ARM64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
